import type { Metadata } from "next";
import { Inter } from "next/font/google";
import DesktopHeader from "./components/header/desktop";
import Footer from "./components/footer";
import StoreProvider from "./StoreProvider";
import ThemeWrapper from "./components/theme-wrapper";
import { Box } from "@mui/material";
import Header from "./components/header";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <ThemeWrapper>
          <StoreProvider>
            <Box>
              <Header />
              <main>
                {children}
              </main>
              <Footer />
            </Box>
          </StoreProvider>
        </ThemeWrapper>
      </body>
    </html>
  );
}
